version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=prod"
    - name: test_Value
      value: "testData"
    - name: MAX
      value: "5"
